package algo.blog.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;

public class DBConnection {
	private static final String DSNAME = "java:comp/env/jdbc/blog";
	private DataSource ds = null;
	private Connection conn = null;
	private PreparedStatement pstmt = null;

	public DBConnection() {
		try {
			Context ctx = new InitialContext();
			ds = (DataSource) ctx.lookup(DSNAME);
			conn = ds.getConnection();
		} catch (NamingException e) {
			e.printStackTrace();
		}catch(SQLException e){
			e.printStackTrace();
		}
	}

	public Connection getConnection() {
		return this.conn;
	}
	
	public PreparedStatement prepareStatement(String sql){
		try {
			if(this.conn!=null)
				pstmt = conn.prepareStatement(sql);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return this.pstmt;
	}
	public PreparedStatement prepareStatement(String sql,int autoGeneratedKeys){
		try {
			if(this.conn!=null)
				pstmt = conn.prepareStatement(sql,autoGeneratedKeys);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return this.pstmt;
	}
	
	public void close(){
		try{
			if(this.pstmt!=null){
				this.pstmt.close();
			}
			if(this.conn!=null){
				this.conn.close();
			}
		}catch(SQLException e){
			e.printStackTrace();
		}
	}
}
