package algo.blog.model;

// Generated 2016-4-5 10:54:45 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Beautypic generated by hbm2java
 */
public class Beautypic implements java.io.Serializable {

	private Integer picId;
	private String name;
	private String urlPath;
	private Date uploadTime;
	private int size;
	private int hot;
	private String comment;
	private boolean deleted;
	private String cn1;
	private Set piccates = new HashSet(0);

	public Beautypic() {
	}

	public Beautypic(String name, String urlPath, Date uploadTime, int size,
			int hot, boolean deleted) {
		this.name = name;
		this.urlPath = urlPath;
		this.uploadTime = uploadTime;
		this.size = size;
		this.hot = hot;
		this.deleted = deleted;
	}

	public Beautypic(String name, String urlPath, Date uploadTime, int size,
			int hot, String comment, boolean deleted, String cn1, Set piccates) {
		this.name = name;
		this.urlPath = urlPath;
		this.uploadTime = uploadTime;
		this.size = size;
		this.hot = hot;
		this.comment = comment;
		this.deleted = deleted;
		this.cn1 = cn1;
		this.piccates = piccates;
	}

	public Integer getPicId() {
		return this.picId;
	}

	public void setPicId(Integer picId) {
		this.picId = picId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrlPath() {
		return this.urlPath;
	}

	public void setUrlPath(String urlPath) {
		this.urlPath = urlPath;
	}

	public Date getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime) {
		this.uploadTime = uploadTime;
	}

	public int getSize() {
		return this.size;
	}

	public void setSize(int size) {
		this.size = size;
	}

	public int getHot() {
		return this.hot;
	}

	public void setHot(int hot) {
		this.hot = hot;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public String getCn1() {
		return this.cn1;
	}

	public void setCn1(String cn1) {
		this.cn1 = cn1;
	}

	public Set getPiccates() {
		return this.piccates;
	}

	public void setPiccates(Set piccates) {
		this.piccates = piccates;
	}

}
