package algo.blog.model;

// Generated 2016-4-5 10:54:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Piccate generated by hbm2java
 */
@SuppressWarnings("serial")
public class Piccate implements java.io.Serializable {

	private Integer cateId;
	private String name;
	private String comment;
	private String cover;
	private short mark;
	private boolean deleted;
	private String cn1;
	@SuppressWarnings("rawtypes")
	private Set beautypics = new HashSet(0);

	public Piccate() {
	}

	public Piccate(String name, String cover, short mark, boolean deleted) {
		this.name = name;
		this.cover = cover;
		this.mark = mark;
		this.deleted = deleted;
	}

	@SuppressWarnings("rawtypes")
	public Piccate(String name, String comment, String cover, short mark,
			boolean deleted, String cn1, Set beautypics) {
		this.name = name;
		this.comment = comment;
		this.cover = cover;
		this.mark = mark;
		this.deleted = deleted;
		this.cn1 = cn1;
		this.beautypics = beautypics;
	}

	public Integer getCateId() {
		return this.cateId;
	}

	public void setCateId(Integer cateId) {
		this.cateId = cateId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getCover() {
		return this.cover;
	}

	public void setCover(String cover) {
		this.cover = cover;
	}

	public short getMark() {
		return this.mark;
	}

	public void setMark(short mark) {
		this.mark = mark;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public String getCn1() {
		return this.cn1;
	}

	public void setCn1(String cn1) {
		this.cn1 = cn1;
	}

	@SuppressWarnings("rawtypes")
	public Set getBeautypics() {
		return this.beautypics;
	}

	@SuppressWarnings("rawtypes")
	public void setBeautypics(Set beautypics) {
		this.beautypics = beautypics;
	}

	@Override
	public String toString() {
		return "Piccate [cateId=" + cateId + ", name=" + name + ", comment="
				+ comment + ", cover=" + cover + ", mark=" + mark
				+ ", deleted=" + deleted + ", cn1=" + cn1 + ", beautypics="
				+ beautypics + "]";
	}
	
	

}
